spring:
  application:
    name: transaction-reconciliation-engine
  datasource:
    url: jdbc:h2:file:./data/reconciliation-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      write-bigdecimal-as-plain: true

app:
  reconciliation:
    timestamp-tolerance-seconds: 5
    sample-internal-path: classpath:data/internal-transactions.json
    sample-provider-path: classpath:data/provider-transactions.json

logging:
  level:
    org.hibernate.SQL: warn
